import { generateService, getSchema } from '@umijs/openapi';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import rimraf from 'rimraf';
import serveStatic from 'serve-static';
import type { IApi } from 'umi';
import { lodash, winPath } from 'umi/plugin-utils';

export default (api: IApi) => {
  // 默认开发启动不加载 Swagger UI、不拉取远程 schema，降低 npm run start 内存与网络负担。@author nokecy
  const enableDevOpenAPI = process.env.DEV_OPENAPI === '1' || process.env.DEV_OPENAPI === 'true';
  api.onStart(() => {
    console.log(`Using openapi Plugin${enableDevOpenAPI ? '' : ' (dev docs disabled)'}`);
  });
  api.describe({
    key: 'openAPI',
    config: {
      schema(joi) {
        const itemSchema = joi.object({
          requestLibPath: joi.string(),
          schemaPath: joi.string(),
          mock: joi.boolean(),
          projectName: joi.string(),
          apiPrefix: joi.alternatives(joi.string(), joi.function()),
          namespace: joi.string(),
          isCamelCase:false,
          hook: joi.object({
            customFunctionName: joi.function(),
            customClassName: joi.function(),
          }),
        });
        return joi.alternatives(joi.array().items(itemSchema), itemSchema);
      },
    },
    enableBy: api.EnableBy.config,
  });
  const { absNodeModulesPath, absTmpPath } = api.paths;
  const openAPIFilesPath = join(absNodeModulesPath!, 'umi_open_api');

  try {
    if (existsSync(openAPIFilesPath)) {
      rimraf.sync(openAPIFilesPath);
    }
    mkdirSync(join(openAPIFilesPath));
  } catch (error) {
    // console.log(error);
  }

  // 增加中间件
  api.addBeforeMiddlewares(() => {
    return [serveStatic(openAPIFilesPath)];
  });

  api.onGenerateFiles(() => {
    if (api.env !== 'development' || !enableDevOpenAPI) return;
    const openAPIConfig = api.config.openAPI;
    const arrayConfig = lodash.flatten([openAPIConfig]);
    const config = arrayConfig?.[0]?.projectName || 'openapi';
    api.writeTmpFile({
      path: join('plugin-openapi', 'openapi.tsx'),
      noPluginDir: true,
      content: `
      // This file is generated by Umi automatically
      // DO NOT CHANGE IT MANUALLY!
      import { useEffect, useState } from 'react';
      import { SwaggerUIBundle } from 'swagger-ui-dist';
      import 'swagger-ui-dist/swagger-ui.css';
      const App = () => {
        const [value, setValue] = useState("${config || 'openapi'}" );
        useEffect(() => {
          SwaggerUIBundle({
            url: \`/umi-plugins_$\{value}.json\`,
            dom_id: '#swagger-ui',
          });
        }, [value]);

        return (
          <div
            style={{
              padding: 24,
            }}
          >
            <select
              style={{
                position: "fixed",
                right: "16px",
                top: "8px",
              }}
              onChange={(e) => setValue(e.target.value)}
            >
              ${arrayConfig
                .map((item) => {
                  return `<option value="${item.projectName || 'openapi'}">${
                    item.projectName || 'openapi'
                  }</option>`;
                })
                .join('\n')}
            </select>
            <div id="swagger-ui" />
          </div>
        );
      };
      export default App;
`,
    });
  });

  if (api.env === 'development' && enableDevOpenAPI) {
    api.modifyRoutes((routes) => {
      routes['umi/plugin/openapi'] = {
        path: '/umi/plugin/openapi',
        absPath: '/umi/plugin/openapi',
        id: 'umi/plugin/openapi',
        file: winPath(join(absTmpPath!, 'plugin-openapi', 'openapi.tsx')),
      };
      return routes;
    });
  }

  const genOpenAPIFiles = async (openAPIConfig: any) => {
    if (api.env !== 'development' || !enableDevOpenAPI) return;
    const openAPIJson = await getSchema(openAPIConfig.schemaPath);
    writeFileSync(
      join(
        openAPIFilesPath,
        `umi-plugins_${openAPIConfig.projectName || 'openapi'}.json`,
      ),
      JSON.stringify(openAPIJson, null, 2),
    );
  };
  api.onDevCompileDone(async () => {
    if (api.env !== 'development' || !enableDevOpenAPI) return;
    try {
      const openAPIConfig = api.config.openAPI;
      if (Array.isArray(openAPIConfig)) {
        openAPIConfig.map((item) => genOpenAPIFiles(item));
        return;
      }
      genOpenAPIFiles(openAPIConfig);
    } catch (error) {
      console.error(error);
    }
  });
  const genAllFiles = async (openAPIConfig: any) => {
    try {
      const packageJsonPath = join(api.cwd, 'package.json');
      if (!existsSync(packageJsonPath)) {
        throw new Error('package.json not found in project root');
      }
      
      const pageConfig = require(packageJsonPath);
      const mockFolder = openAPIConfig.mock ? join(api.cwd, 'mock') : undefined;
      const serversFolder = join(api.cwd, 'src', 'services');
      const srcFolder = join(api.cwd, 'src');
      
      // 确保 src 目录存在
      if (!existsSync(srcFolder)) {
        api.logger.info('[openAPI]: Creating src directory');
        mkdirSync(srcFolder, { recursive: true });
      }
      
      // 如果 services 目录不存在，创建它
      if (!existsSync(serversFolder)) {
        api.logger.info('[openAPI]: Creating src/services directory');
        mkdirSync(serversFolder, { recursive: true });
      }
      
      // 如果 mock 目录不存在，创建它
      if (mockFolder && !existsSync(mockFolder)) {
        api.logger.info('[openAPI]: Creating mock directory');
        mkdirSync(mockFolder, { recursive: true });
      }

      await generateService({
        projectName: pageConfig.name.split('/').pop(),
        ...openAPIConfig,
        serversPath: serversFolder,
        mockFolder,
      });
      api.logger.info('[openAPI]: execution complete');
    } catch (error) {
      api.logger.error(`[openAPI]: Error in genAllFiles: ${error.message}`);
      throw error;
    }
  };
  api.registerCommand({
    name: 'openapi',
    fn: async () => {
      const openAPIConfig = api.config.openAPI;
      if (!openAPIConfig) {
        api.logger.error('[openAPI]: openAPI config is required in .umirc.ts or config/config.ts');
        return;
      }
      
      try {
        if (Array.isArray(openAPIConfig)) {
          await Promise.all(openAPIConfig.map((item) => genAllFiles(item)));
          return;
        }
        await genAllFiles(openAPIConfig);
      } catch (error) {
        api.logger.error(`[openAPI]: Failed to generate API services: ${error.message}`);
        throw error;
      }
    },
  });
};
